spring.application.name=TaskTracker
server.port=8090

spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}

spring.datasource.url=jdbc:mysql://localhost:3306/task_tracker
spring.datasource.username=root
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
logging.level.ROOT=INFO
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.springframework.transaction=DEBUG;
#logging.level.org.springframework.security=DEBUG



spring.app.jwtSecret=${SPRING_APP_JWT_SECRET}
spring.app.jwtExpirationMs=${SPRING_APP_JWT_EXPIRATION_MS}

# email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# GitHub OAuth2 configuration
spring.security.oauth2.client.registration.github.client-id=Ov23liQFikV3Z3hAdKfB
spring.security.oauth2.client.registration.github.client-secret=e2bc56aa5b797bb5c32ac9ab27c0f5dbc1d1718a
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=235306234713-jlg0tn9494toac2tf3vcbf2pr0598vgv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

frontend.url=${FRONTEND_URL}

logging.level.org.springframework.security=TRACE